-- ============================================================
-- supabase/seed.sql(在 db reset 后自动执行;幂等,可重复运行)
-- 内置角色 + 演示数据
-- 权限码与前端 views 的 meta.auth 对应;角色可配置,可在此追加
-- ============================================================

-- 内置角色:运维管理员 / 店长 / 店员 / 收银员 / 医生
-- scope 语义(S30-R01):system=平台级;tenant=租户级(须租户级分配 store_id IS NULL);
-- store=门店级(须带 store_id 分配,禁止提升为租户级权限)
insert into public.roles (code, name, description, permissions, is_system, scope) values
  ('system_admin', '运维管理员', '平台运维方,管理所有店铺/角色/用户', array[
    'appointment.manage',
    'appointment.view',
    'catalog.drug.manage',
    'catalog.manage',
    'catalog.storePrice.manage',
    'catalog.vaccine.manage',
    'catalog.view',
    'customer.archive',
    'customer.create',
    'customer.import',
    'customer.merge',
    'customer.update',
    'customer.view',
    'daily_closing.adjust',
    'daily_closing.close',
    'daily_closing.read',
    'deworming.manage',
    'deworming.view',
    'diag_reminder.view',
    'employee.assignStore',
    'employee.changeRole',
    'employee.create',
    'employee.disable',
    'employee.enable',
    'employee.invite',
    'employee.update',
    'encounter.revise',
    'encounter.sign',
    'encounter.view',
    'encounter.work',
    'epidemic.read',
    'epidemic.report',
    'epidemic.resolve',
    'file.archive',
    'file.delete',
    'file.download',
    'file.upload',
    'handover.manage',
    'imports.manage',
    'inpatient.admit',
    'inpatient.discharge',
    'inpatient.transfer',
    'inpatient.view',
    'inventory.confirm',
    'inventory.count',
    'inventory.dispense',
    'inventory.manage',
    'inventory.receive',
    'inventory.release',
    'inventory.reserve',
    'inventory.transfer',
    'inventory.view',
    'invoice.cancel',
    'invoice.confirm',
    'invoice.create',
    'invoice.view',
    'lab.collect',
    'lab.critical.acknowledge',
    'lab.request',
    'lab.result.input',
    'lab.result.review',
    'lab.view',
    'lab_critical.execute',
    'lab_critical.read',
    'lab_critical.write',
    'lab_sample.execute',
    'lab_sample.read',
    'lab_sample.write',
    'license.manage',
    'license.read',
    'medical_record.amend.approve',
    'medical_record.amend.request',
    'medical_record.archive',
    'membership.manage',
    'membership.view',
    'message.manage',
    'nurse_task.manage',
    'nurse_task.view',
    'nursing.manage',
    'nursing.view',
    'payment.process',
    'payment_context.read',
    'pet.create',
    'pet.update',
    'pet.view',
    'points.adjust',
    'prescription.controlled_issue',
    'prescription.create',
    'prescription.dispense',
    'prescription.extend_validity',
    'prescription.issue',
    'prescription.view',
    'print.manage',
    'print.setting.read',
    'progress.sign',
    'progress.view',
    'progress.write',
    'receipt.print',
    'reconciliation.confirm',
    'reconciliation.edit',
    'reconciliation.read',
    'refund.process',
    'regulatory_report.generate',
    'regulatory_report.read',
    'regulatory_report.submit',
    'reminder.manage',
    'reports.view',
    'role.create',
    'role.permission.update',
    'role.update',
    'security.view',
    'settlement.execute',
    'settlement.view',
    'settlement.write',
    'store.archive',
    'store.create',
    'store.restore',
    'store.update',
    'store:view',
    'system.user.create',
    'system.user.resetPassword',
    'system:role:manage',
    'system:store:manage',
    'system:user:manage',
    'tenant.initialization.read',
    'tenant.initialize',
    'tenant.membership.create',
    'tenant.membership.update',
    'vaccine.certificate.issue',
    'vaccine.manage',
    'vaccine.view',
    'veterinarian_registration.manage',
    'veterinarian_registration.read',
    'waste.manage',
    'waste.read'
  ], true, 'system'),
  ('store_manager', '店长', '管理本店成员与日常运营', array[
    'appointment.manage',
    'appointment.view',
    'catalog.storePrice.manage',
    'catalog.view',
    'customer.archive',
    'customer.create',
    'customer.import',
    'customer.update',
    'customer.view',
    'daily_closing.close',
    'daily_closing.read',
    'deworming.manage',
    'deworming.view',
    'diag_reminder.view',
    'employee.assignStore',
    'employee.changeRole',
    'employee.create',
    'employee.disable',
    'employee.enable',
    'employee.invite',
    'employee.update',
    'encounter.revise',
    'encounter.sign',
    'encounter.view',
    'encounter.work',
    'epidemic.read',
    'epidemic.report',
    'epidemic.resolve',
    'file.archive',
    'file.download',
    'file.upload',
    'handover.manage',
    'imports.manage',
    'inpatient.admit',
    'inpatient.discharge',
    'inpatient.transfer',
    'inpatient.view',
    'inventory.confirm',
    'inventory.count',
    'inventory.dispense',
    'inventory.receive',
    'inventory.release',
    'inventory.reserve',
    'inventory.transfer',
    'inventory.view',
    'invoice.cancel',
    'invoice.confirm',
    'invoice.create',
    'invoice.view',
    'lab.collect',
    'lab.critical.acknowledge',
    'lab.request',
    'lab.result.input',
    'lab.result.review',
    'lab.view',
    'lab_critical.execute',
    'lab_critical.read',
    'lab_critical.write',
    'lab_sample.execute',
    'lab_sample.read',
    'lab_sample.write',
    'license.manage',
    'license.read',
    'medical_record.amend.approve',
    'medical_record.amend.request',
    'medical_record.archive',
    'membership.manage',
    'membership.view',
    'message.manage',
    'nurse_task.manage',
    'nurse_task.view',
    'nursing.manage',
    'nursing.view',
    'payment.process',
    'pet.create',
    'pet.update',
    'pet.view',
    'points.adjust',
    'prescription.controlled_issue',
    'prescription.create',
    'prescription.dispense',
    'prescription.extend_validity',
    'prescription.issue',
    'prescription.view',
    'print.manage',
    'progress.sign',
    'progress.view',
    'progress.write',
    'receipt.print',
    'reconciliation.confirm',
    'reconciliation.edit',
    'reconciliation.read',
    'refund.process',
    'regulatory_report.read',
    'reminder.manage',
    'reports.view',
    'settlement.execute',
    'settlement.view',
    'settlement.write',
    'store.update',
    'store:view',
    'system.user.create',
    'system:user:manage',
    'vaccine.certificate.issue',
    'vaccine.manage',
    'vaccine.view',
    'waste.manage',
    'waste.read'
  ], true, 'store'),
  ('staff', '店员', '门店工作人员', array[
    'store:view'
  ], true, 'store'),
  ('cashier', '收银员', '负责收银', array[
    'daily_closing.read',
    'invoice.create',
    'invoice.view',
    'payment.process',
    'receipt.print',
    'reconciliation.read',
    'refund.process',
    'settlement.view',
    'settlement.write',
    'store:view'
  ], true, 'store'),
  ('doctor', '医生', '诊疗/处方/检验报告(门店级角色)', array[
    'appointment.manage',
    'appointment.view',
    'catalog.view',
    'customer.create',
    'customer.update',
    'customer.view',
    'deworming.manage',
    'deworming.view',
    'diag_reminder.view',
    'encounter.revise',
    'encounter.sign',
    'encounter.view',
    'encounter.work',
    'epidemic.read',
    'epidemic.report',
    'handover.manage',
    'inpatient.admit',
    'inpatient.discharge',
    'inpatient.transfer',
    'inpatient.view',
    'lab.collect',
    'lab.request',
    'lab.result.input',
    'lab.result.review',
    'lab.view',
    'lab_critical.execute',
    'lab_critical.read',
    'lab_critical.write',
    'lab_sample.read',
    'lab_sample.write',
    'license.read',
    'medical_record.amend.request',
    'medical_record.archive',
    'nurse_task.manage',
    'nurse_task.view',
    'nursing.manage',
    'nursing.view',
    'pet.create',
    'pet.update',
    'pet.view',
    'prescription.controlled_issue',
    'prescription.create',
    'prescription.issue',
    'prescription.view',
    'progress.sign',
    'progress.view',
    'progress.write',
    'regulatory_report.read',
    'settlement.view',
    'store:view',
    'vaccine.certificate.issue',
    'vaccine.manage',
    'vaccine.view',
    'waste.read'
  ], true, 'store'),
  ('nurse', '护士', '执行护理/标本/检验任务(门店级角色)', array[
    'deworming.manage',
    'deworming.view',
    'diag_reminder.view',
    'handover.manage',
    'inpatient.view',
    'lab.collect',
    'lab.result.input',
    'lab.view',
    'lab_critical.read',
    'lab_sample.execute',
    'lab_sample.read',
    'lab_sample.write',
    'nursing.manage',
    'nursing.view',
    'progress.view',
    'vaccine.manage',
    'vaccine.view'
  ], true, 'store'),
  ('tenant_owner', '租户所有者', '租户级管理角色,可维护本租户执业兽医备案及监管运营数据', array[
    'daily_closing.adjust',
    'daily_closing.close',
    'daily_closing.read',
    'epidemic.read',
    'epidemic.report',
    'epidemic.resolve',
    'license.manage',
    'license.read',
    'payment_context.read',
    'print.setting.read',
    'reconciliation.confirm',
    'reconciliation.edit',
    'reconciliation.read',
    'regulatory_report.generate',
    'regulatory_report.read',
    'regulatory_report.submit',
    'tenant.initialization.read',
    'tenant.initialize',
    'veterinarian_registration.manage',
    'veterinarian_registration.read',
    'waste.manage',
    'waste.read'
  ], true, 'tenant')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  permissions = excluded.permissions,
  is_system = excluded.is_system,
  scope = excluded.scope;

-- 权限目录种子(MXQ-3004;code 唯一,幂等)
insert into public.permissions (code, name, module) values
  ('system:user:manage', '用户管理', 'system'),
  ('system:role:manage', '角色管理', 'system'),
  ('system:store:manage', '店铺管理', 'system'),
  ('system.user.create', '创建用户', 'system'),
  ('system.user.resetPassword', '重置用户密码', 'system'),
  ('store:view', '查看门店', 'store'),
  ('store.create', '创建门店', 'store'),
  ('store.update', '编辑门店', 'store'),
  ('tenant.membership.create', '添加租户成员', 'tenant'),
  ('tenant.membership.update', '更新租户成员', 'tenant'),
  ('employee.create', '创建员工', 'employee'),
  ('employee.update', '编辑员工', 'employee'),
  ('employee.assignStore', '分配门店', 'employee'),
  ('employee.changeRole', '变更角色', 'employee'),
  ('role.create', '创建角色', 'role'),
  ('role.update', '编辑角色', 'role'),
  -- S3.1-A:租户初始化权限
  ('tenant.initialize', '初始化租户', 'tenant'),
  ('tenant.initialization.read', '查看租户初始化状态', 'tenant'),
  ('payment_context.read', '查看支付上下文', 'billing'),
  ('print.setting.read', '查看打印设置', 'operations'),
  -- S31-PARALLEL-B:日结与对账权限码(与 migration 39/41 保持一致)
  ('daily_closing.read', '查看日结', 'closing'),
  ('daily_closing.close', '执行日结', 'closing'),
  ('daily_closing.adjust', '调整日结', 'closing'),
  ('reconciliation.read', '查看对账', 'closing'),
  ('reconciliation.edit', '录入对账实际金额', 'closing'),
  ('reconciliation.confirm', '确认对账差异', 'closing'),
  -- S31-C:医疗闭环增强权限码(与 migration 45~49 保持一致)
  ('lab_sample.read', '查看检验标本', 'lab'),
  ('lab_sample.write', '管理检验标本', 'lab'),
  ('lab_sample.execute', '执行标本流转', 'lab'),
  ('lab_critical.read', '查看危急值', 'lab'),
  ('lab_critical.write', '管理危急值', 'lab'),
  ('lab_critical.execute', '通知/确认危急值', 'lab'),
  ('progress.view', '查看住院病程', 'inpatient'),
  ('progress.write', '记录住院病程', 'inpatient'),
  ('progress.sign', '签署住院病程', 'inpatient'),
  ('settlement.view', '查看出院结算', 'inpatient'),
  ('settlement.write', '结算收款', 'inpatient'),
  ('settlement.execute', '减免/完成结算', 'inpatient')
on conflict (code) do update set
  name = excluded.name,
  module = excluded.module;

-- 演示数据(可选):给指定账号设置演示权限(把邮箱换成你的登录账号)
update public.profiles
set permissions = array[
  'pages.general:browse',
  'pages.form:browse',
  'pages.list:browse',
  'pages.shop:browse'
]
where account = 'admin@example.com';

-- standard_module 示例数据(幂等)
insert into public.standard_module (title)
select v.title
from (values
  ('示例标题一'),
  ('示例标题二'),
  ('示例标题三')
) as v(title)
where not exists (
  select 1 from public.standard_module
  where title = v.title
);
