-- ============================================================
-- supabase/seed.sql(在 db reset 后自动执行;幂等,可重复运行)
-- 内置角色 + 演示数据
-- 权限码与前端 views 的 meta.auth 对应;角色可配置,可在此追加
-- ============================================================

-- 内置角色:运维管理员 / 店长 / 店员 / 收银员 / 医生
-- scope 语义(S30-R01):system=平台级;tenant=租户级(须租户级分配 store_id IS NULL);
-- store=门店级(须带 store_id 分配,禁止提升为租户级权限)
insert into public.roles (code, name, description, permissions, is_system, scope) values
  ('system_admin', '运维管理员', '平台运维方,管理所有店铺/角色/用户', array[
    'appointment.manage',
    'appointment.view',
    'catalog.drug.manage',
    'catalog.manage',
    'catalog.storePrice.manage',
    'catalog.vaccine.manage',
    'catalog.view',
    'customer.archive',
    'customer.create',
    'customer.import',
    'customer.merge',
    'customer.update',
    'customer.view',
    'daily_closing.adjust',
    'daily_closing.close',
    'daily_closing.read',
    'deworming.manage',
    'deworming.view',
    'diag_reminder.view',
    'employee.assignStore',
    'employee.changeRole',
    'employee.create',
    'employee.disable',
    'employee.enable',
    'employee.invite',
    'employee.update',
    'encounter.revise',
    'encounter.sign',
    'encounter.view',
    'encounter.work',
    'epidemic.read',
    'epidemic.report',
    'epidemic.resolve',
    'file.archive',
    'file.delete',
    'file.download',
    'file.upload',
    'handover.manage',
    'imports.manage',
    'inpatient.admit',
    'inpatient.discharge',
    'inpatient.transfer',
    'inpatient.view',
    'inventory.confirm',
    'inventory.count',
    'inventory.dispense',
    'inventory.manage',
    'inventory.receive',
    'inventory.release',
    'inventory.reserve',
    'inventory.transfer',
    'inventory.write_off',
    'inventory.view',
    'invoice.cancel',
    'invoice.confirm',
    'invoice.create',
    'invoice.view',
    'lab.collect',
    'lab.critical.acknowledge',
    'lab.request',
    'lab.result.input',
    'lab.result.review',
    'lab.result.revise',
    'lab.view',
    'lab_critical.execute',
    'lab_critical.read',
    'lab_critical.write',
    'lab_sample.execute',
    'lab_sample.read',
    'lab_sample.write',
    'license.manage',
    'license.read',
    'medical_record.amend.approve',
    'medical_record.amend.request',
    'medical_record.archive',
    'membership.manage',
    'membership.view',
    'message.manage',
    'nurse_task.manage',
    'nurse_task.view',
    'nursing.manage',
    'nursing.view',
    'payment.process',
    'payment_context.read',
    'pet.create',
    'pet.update',
    'pet.view',
    'points.adjust',
    'prescription.controlled_issue',
    'prescription.create',
    'prescription.dispense',
    'prescription.extend_validity',
    'prescription.issue',
    'prescription.view',
    'print.manage',
    'print.setting.read',
    'progress.sign',
    'progress.view',
    'progress.write',
    'receipt.print',
    'reconciliation.confirm',
    'reconciliation.edit',
    'reconciliation.read',
    'refund.process',
    'regulatory_report.generate',
    'regulatory_report.read',
    'regulatory_report.submit',
    'reminder.manage',
    'reports.view',
    'role.create',
    'role.permission.update',
    'role.update',
    'security.view',
    'settlement.execute',
    'settlement.view',
    'settlement.write',
    'store.archive',
    'store.create',
    'store.restore',
    'store.update',
    'store:view',
    'system.user.create',
    'system.user.resetPassword',
    'system:role:manage',
    'system:store:manage',
    'system:user:manage',
    'tenant.initialization.read',
    'tenant.initialize',
    'tenant.membership.create',
    'tenant.membership.update',
    'vaccine.certificate.issue',
    'vaccine.manage',
    'vaccine.view',
    'veterinarian_registration.manage',
    'veterinarian_registration.read',
    'waste.manage',
    'waste.read',
    -- S3.1 P1:Seed Permission Array Drift - 补齐后续新增域权限
    'store.archive',
    'store.restore',
    'employee.invite',
    'employee.disable',
    'employee.enable',
    'role.permission.update',
    'file.upload',
    'file.download',
    'file.archive',
    'file.delete',
    'followup.view',
    'followup.manage',
    'followup.complete',
    'supplier.view',
    'supplier.manage',
    'purchase.view',
    'purchase.create',
    'purchase.submit',
    'purchase.approve',
    'purchase.receive',
    'purchase.post',
    'imaging.view',
    'imaging.order',
    'imaging.perform',
    'imaging.report',
    'imaging.review',
    'imaging.publish',
    'boarding.view',
    'boarding.manage',
    'boarding.care',
    'boarding.checkout',
    'imports.view',
    'imports.create',
    'imports.execute',
    'imports.cancel',
    'documents.view',
    'documents.print',
    'documents.template.manage',
    'analytics.view.store',
    'analytics.view.tenant',
    'analytics.export',
    'audit.view',
    'audit.export',
    'approval.inbox.view',
    'settings.tenant.read',
    'settings.tenant.manage',
    'settings.store.read',
    'settings.store.manage',
    'platform.tenant.list',
    'platform.tenant.read',
    'platform.tenant.suspend',
    'platform.tenant.resume',
    'points.view'
  ], true, 'system'),
  ('store_manager', '店长', '管理本店成员与日常运营', array[
    'appointment.manage',
    'appointment.view',
    'catalog.storePrice.manage',
    'catalog.view',
    'customer.archive',
    'customer.create',
    'customer.import',
    'customer.update',
    'customer.view',
    'daily_closing.close',
    'daily_closing.read',
    'deworming.manage',
    'deworming.view',
    'diag_reminder.view',
    'employee.assignStore',
    'employee.changeRole',
    'employee.create',
    'employee.disable',
    'employee.enable',
    'employee.invite',
    'employee.update',
    'encounter.revise',
    'encounter.sign',
    'encounter.view',
    'encounter.work',
    'epidemic.read',
    'epidemic.report',
    'epidemic.resolve',
    'file.archive',
    'file.download',
    'file.upload',
    'handover.manage',
    'imports.manage',
    'inpatient.admit',
    'inpatient.discharge',
    'inpatient.transfer',
    'inpatient.view',
    'inventory.confirm',
    'inventory.count',
    'inventory.dispense',
    'inventory.receive',
    'inventory.release',
    'inventory.reserve',
    'inventory.transfer',
    'inventory.write_off',
    'inventory.view',
    'invoice.cancel',
    'invoice.confirm',
    'invoice.create',
    'invoice.view',
    'lab.collect',
    'lab.critical.acknowledge',
    'lab.request',
    'lab.result.input',
    'lab.result.review',
    'lab.result.revise',
    'lab.view',
    'lab_critical.execute',
    'lab_critical.read',
    'lab_critical.write',
    'lab_sample.execute',
    'lab_sample.read',
    'lab_sample.write',
    'license.manage',
    'license.read',
    'medical_record.amend.approve',
    'medical_record.amend.request',
    'medical_record.archive',
    'membership.manage',
    'membership.view',
    'message.manage',
    'nurse_task.manage',
    'nurse_task.view',
    'nursing.manage',
    'nursing.view',
    'payment.process',
    'pet.create',
    'pet.update',
    'pet.view',
    'points.adjust',
    'prescription.controlled_issue',
    'prescription.create',
    'prescription.dispense',
    'prescription.extend_validity',
    'prescription.issue',
    'prescription.view',
    'print.manage',
    'progress.sign',
    'progress.view',
    'progress.write',
    'receipt.print',
    'reconciliation.confirm',
    'reconciliation.edit',
    'reconciliation.read',
    'refund.process',
    'regulatory_report.read',
    'reminder.manage',
    'reports.view',
    'settlement.execute',
    'settlement.view',
    'settlement.write',
    'store.update',
    'store:view',
    'system.user.create',
    'system:user:manage',
    'vaccine.certificate.issue',
    'vaccine.manage',
    'vaccine.view',
    'waste.manage',
    'waste.read',
    -- S3.1 P1:Seed Permission Array Drift - 补齐后续新增域权限
    'employee.invite',
    'employee.disable',
    'employee.enable',
    'role.permission.update',
    'file.upload',
    'file.download',
    'file.archive',
    'file.delete',
    'followup.view',
    'followup.manage',
    'followup.complete',
    'supplier.view',
    'supplier.manage',
    'purchase.view',
    'purchase.create',
    'purchase.submit',
    'purchase.approve',
    'purchase.receive',
    'purchase.post',
    'imaging.view',
    'imaging.order',
    'imaging.perform',
    'imaging.report',
    'imaging.review',
    'imaging.publish',
    'boarding.view',
    'boarding.manage',
    'boarding.care',
    'boarding.checkout',
    'imports.view',
    'imports.create',
    'imports.execute',
    'imports.cancel',
    'documents.view',
    'documents.print',
    'documents.template.manage',
    'analytics.view.store',
    'analytics.export',
    'audit.view',
    'approval.inbox.view',
    'settings.tenant.read',
    'settings.tenant.manage',
    'settings.store.read',
    'settings.store.manage',
    'points.view'
  ], true, 'store'),
  ('staff', '店员', '门店工作人员', array[
    'store:view'
  ], true, 'store'),
  ('cashier', '收银员', '负责收银', array[
    'daily_closing.read',
    'invoice.create',
    'invoice.view',
    'payment.process',
    'receipt.print',
    'reconciliation.read',
    'refund.process',
    'settlement.view',
    'settlement.write',
    'store:view'
  ], true, 'store'),
  ('doctor', '医生', '诊疗/处方/检验报告(门店级角色)', array[
    'appointment.manage',
    'appointment.view',
    'catalog.view',
    'customer.create',
    'customer.update',
    'customer.view',
    'deworming.manage',
    'deworming.view',
    'diag_reminder.view',
    'encounter.revise',
    'encounter.sign',
    'encounter.view',
    'encounter.work',
    'epidemic.read',
    'epidemic.report',
    'handover.manage',
    'inpatient.admit',
    'inpatient.discharge',
    'inpatient.transfer',
    'inpatient.view',
    'lab.collect',
    'lab.request',
    'lab.result.input',
    'lab.result.review',
    'lab.result.revise',
    'lab.view',
    'lab_critical.execute',
    'lab_critical.read',
    'lab_critical.write',
    'lab_sample.read',
    'lab_sample.write',
    'license.read',
    'medical_record.amend.request',
    'medical_record.archive',
    'nurse_task.manage',
    'nurse_task.view',
    'nursing.manage',
    'nursing.view',
    'pet.create',
    'pet.update',
    'pet.view',
    'prescription.controlled_issue',
    'prescription.create',
    'prescription.issue',
    'prescription.view',
    'progress.sign',
    'progress.view',
    'progress.write',
    'regulatory_report.read',
    'settlement.view',
    'store:view',
    'vaccine.certificate.issue',
    'vaccine.manage',
    'vaccine.view',
    'waste.read',
    -- S3.1 P1:Seed Permission Array Drift - 补齐后续新增域权限
    'followup.view',
    'imaging.view',
    'imaging.order',
    'imaging.report',
    'boarding.view',
    'documents.view',
    'audit.view',
    'file.upload',
    'file.download'
  ], true, 'store'),
  ('nurse', '护士', '执行护理/标本/检验任务(门店级角色)', array[
    'deworming.manage',
    'deworming.view',
    'diag_reminder.view',
    'handover.manage',
    'inpatient.view',
    'lab.collect',
    'lab.result.input',
    'lab.view',
    'lab_critical.read',
    'lab_sample.execute',
    'lab_sample.read',
    'lab_sample.write',
    'nursing.manage',
    'nursing.view',
    'progress.view',
    'vaccine.manage',
    'vaccine.view',
    -- S3.1 P1:Seed Permission Array Drift - 补齐后续新增域权限
    'imaging.view',
    'boarding.view',
    'boarding.care',
    'file.upload',
    'file.download'
  ], true, 'store'),
  ('tenant_owner', '租户所有者', '租户级管理角色,可维护本租户执业兽医备案及监管运营数据', array[
    'daily_closing.adjust',
    'daily_closing.close',
    'daily_closing.read',
    'epidemic.read',
    'epidemic.report',
    'epidemic.resolve',
    'license.manage',
    'license.read',
    'payment_context.read',
    'print.setting.read',
    'reconciliation.confirm',
    'reconciliation.edit',
    'reconciliation.read',
    'regulatory_report.generate',
    'regulatory_report.read',
    'regulatory_report.submit',
    'tenant.initialization.read',
    'tenant.initialize',
    'veterinarian_registration.manage',
    'veterinarian_registration.read',
    'waste.manage',
    'waste.read',
    -- S3.1 P1:Seed Permission Array Drift - 补齐后续新增域权限
    'tenant.membership.create',
    'tenant.membership.update',
    'file.upload',
    'file.download',
    'file.archive',
    'file.delete',
    'documents.view',
    'documents.print',
    'analytics.view.tenant',
    'analytics.export',
    'audit.view',
    'approval.inbox.view',
    'settings.tenant.read',
    'settings.tenant.manage'
  ], true, 'tenant')
on conflict (code) do update set
  name = excluded.name,
  description = excluded.description,
  permissions = excluded.permissions,
  is_system = excluded.is_system,
  scope = excluded.scope;

-- 权限目录种子(MXQ-3004;code 唯一,幂等)
insert into public.permissions (code, name, module) values
  ('system:user:manage', '用户管理', 'system'),
  ('system:role:manage', '角色管理', 'system'),
  ('system:store:manage', '店铺管理', 'system'),
  ('system.user.create', '创建用户', 'system'),
  ('system.user.resetPassword', '重置用户密码', 'system'),
  ('store:view', '查看门店', 'store'),
  ('store.create', '创建门店', 'store'),
  ('store.update', '编辑门店', 'store'),
  ('tenant.membership.create', '添加租户成员', 'tenant'),
  ('tenant.membership.update', '更新租户成员', 'tenant'),
  ('employee.create', '创建员工', 'employee'),
  ('employee.update', '编辑员工', 'employee'),
  ('employee.assignStore', '分配门店', 'employee'),
  ('employee.changeRole', '变更角色', 'employee'),
  ('role.create', '创建角色', 'role'),
  ('role.update', '编辑角色', 'role'),
  -- S3.1-A:租户初始化权限
  ('tenant.initialize', '初始化租户', 'tenant'),
  ('tenant.initialization.read', '查看租户初始化状态', 'tenant'),
  ('payment_context.read', '查看支付上下文', 'billing'),
  ('print.setting.read', '查看打印设置', 'operations'),
  -- S31-PARALLEL-B:日结与对账权限码(与 migration 39/41 保持一致)
  ('daily_closing.read', '查看日结', 'closing'),
  ('daily_closing.close', '执行日结', 'closing'),
  ('daily_closing.adjust', '调整日结', 'closing'),
  ('reconciliation.read', '查看对账', 'closing'),
  ('reconciliation.edit', '录入对账实际金额', 'closing'),
  ('reconciliation.confirm', '确认对账差异', 'closing'),
  -- S31-C:医疗闭环增强权限码(与 migration 45~49 保持一致)
  ('lab_sample.read', '查看检验标本', 'lab'),
  ('lab_sample.write', '管理检验标本', 'lab'),
  ('lab_sample.execute', '执行标本流转', 'lab'),
  ('lab_critical.read', '查看危急值', 'lab'),
  ('lab_critical.write', '管理危急值', 'lab'),
  ('lab_critical.execute', '通知/确认危急值', 'lab'),
  ('progress.view', '查看住院病程', 'inpatient'),
  ('progress.write', '记录住院病程', 'inpatient'),
  ('progress.sign', '签署住院病程', 'inpatient'),
  ('settlement.view', '查看出院结算', 'inpatient'),
  ('settlement.write', '结算收款', 'inpatient'),
  ('settlement.execute', '减免/完成结算', 'inpatient'),
  -- 以下为前端 PERMISSIONS 目录同步(S3.1 P1:Seed Permission Array Drift,与 views/system/permissions.ts 对齐)
  ('store.archive', '归档门店', 'store'),
  ('store.restore', '恢复门店', 'store'),
  ('employee.invite', '邀请员工', 'employee'),
  ('employee.disable', '停用员工', 'employee'),
  ('employee.enable', '启用员工', 'employee'),
  ('role.permission.update', '编辑角色权限', 'role'),
  ('file.upload', '上传文件', 'file'),
  ('file.download', '下载文件', 'file'),
  ('file.archive', '归档文件', 'file'),
  ('file.delete', '删除文件', 'file'),
  ('customer.view', '查看客户', 'crm'),
  ('customer.create', '创建客户', 'crm'),
  ('customer.update', '编辑客户', 'crm'),
  ('customer.archive', '归档客户', 'crm'),
  ('customer.merge', '合并客户', 'crm'),
  ('customer.import', '导入客户', 'crm'),
  ('pet.view', '查看宠物', 'crm'),
  ('pet.create', '创建宠物', 'crm'),
  ('pet.update', '编辑宠物', 'crm'),
  ('followup.view', '查看回访', 'crm'),
  ('followup.manage', '管理回访', 'crm'),
  ('followup.complete', '完成回访', 'crm'),
  ('catalog.view', '查看目录', 'catalog'),
  ('catalog.manage', '管理目录', 'catalog'),
  ('catalog.storePrice.manage', '管理门店价格', 'catalog'),
  ('catalog.drug.manage', '管理药品扩展', 'catalog'),
  ('catalog.vaccine.manage', '管理疫苗扩展', 'catalog'),
  ('appointment.view', '查看预约', 'clinical'),
  ('appointment.manage', '管理预约', 'clinical'),
  ('encounter.view', '查看病历', 'clinical'),
  ('encounter.work', '接诊编辑', 'clinical'),
  ('encounter.sign', '签署病历', 'clinical'),
  ('encounter.revise', '修订病历', 'clinical'),
  ('prescription.view', '查看处方', 'clinical'),
  ('prescription.create', '开具处方', 'clinical'),
  ('prescription.dispense', '发药', 'clinical'),
  ('prescription.issue', '开具处方', 'clinical'),
  ('prescription.extend_validity', '延长处方有效期', 'clinical'),
  ('prescription.controlled_issue', '开具受控药品处方', 'clinical'),
  ('nurse_task.view', '查看护士任务', 'clinical'),
  ('nurse_task.manage', '管理护士任务', 'clinical'),
  ('invoice.view', '查看发票', 'billing'),
  ('invoice.create', '创建发票', 'billing'),
  ('invoice.confirm', '确认发票', 'billing'),
  ('invoice.cancel', '取消发票', 'billing'),
  ('payment.process', '处理支付', 'billing'),
  ('refund.process', '处理退款', 'billing'),
  ('receipt.print', '打印小票', 'billing'),
  ('inventory.view', '查看库存', 'inventory'),
  ('inventory.receive', '入库', 'inventory'),
  ('inventory.dispense', '发药', 'inventory'),
  ('inventory.count', '盘点', 'inventory'),
  ('inventory.transfer', '调拨', 'inventory'),
  ('inventory.write_off', '库存报损', 'inventory'),
  ('inventory.manage', '仓库管理', 'inventory'),
  ('supplier.view', '查看供应商', 'inventory'),
  ('supplier.manage', '管理供应商', 'inventory'),
  ('purchase.view', '查看采购单', 'inventory'),
  ('purchase.create', '创建采购单', 'inventory'),
  ('purchase.submit', '提交采购单', 'inventory'),
  ('purchase.approve', '审核采购单', 'inventory'),
  ('purchase.receive', '采购收货', 'inventory'),
  ('purchase.post', '采购过账', 'inventory'),
  ('vaccine.view', '查看疫苗', 'diagnostics'),
  ('vaccine.manage', '管理疫苗', 'diagnostics'),
  ('vaccine.certificate.issue', '签发疫苗证明', 'diagnostics'),
  ('deworming.view', '查看驱虫', 'diagnostics'),
  ('deworming.manage', '管理驱虫', 'diagnostics'),
  ('lab.view', '查看检验', 'diagnostics'),
  ('lab.request', '申请检验', 'diagnostics'),
  ('lab.collect', '采集标本', 'diagnostics'),
  ('lab.result.input', '录入结果', 'diagnostics'),
  ('lab.result.review', '审核结果', 'diagnostics'),
  ('lab.result.revise', '修订结果', 'diagnostics'),
  ('lab.critical.acknowledge', '确认危急值', 'diagnostics'),
  ('diag_reminder.view', '查看提醒', 'diagnostics'),
  ('imaging.view', '查看影像', 'diagnostics'),
  ('imaging.order', '申请影像', 'diagnostics'),
  ('imaging.perform', '执行影像', 'diagnostics'),
  ('imaging.report', '编写影像报告', 'diagnostics'),
  ('imaging.review', '审核影像报告', 'diagnostics'),
  ('imaging.publish', '发布影像报告', 'diagnostics'),
  ('inpatient.view', '查看住院', 'inpatient'),
  ('inpatient.admit', '办理入院', 'inpatient'),
  ('inpatient.discharge', '办理出院', 'inpatient'),
  ('inpatient.transfer', '换房', 'inpatient'),
  ('nursing.view', '查看护理', 'inpatient'),
  ('nursing.manage', '管理护理', 'inpatient'),
  ('handover.manage', '交接班', 'inpatient'),
  ('boarding.view', '查看寄养', 'boarding'),
  ('boarding.manage', '管理寄养', 'boarding'),
  ('boarding.care', '寄养照护', 'boarding'),
  ('boarding.checkout', '寄养离店', 'boarding'),
  ('membership.view', '查看会员等级', 'operations'),
  ('membership.manage', '管理会员等级', 'operations'),
  ('points.view', '查看积分流水', 'operations'),
  ('points.adjust', '调整积分', 'operations'),
  ('message.manage', '管理消息模板', 'operations'),
  ('reminder.manage', '管理提醒', 'operations'),
  ('imports.view', '查看导入任务', 'operations'),
  ('imports.create', '新建导入', 'operations'),
  ('imports.execute', '执行导入', 'operations'),
  ('imports.cancel', '取消导入', 'operations'),
  ('imports.manage', '管理导入任务', 'operations'),
  ('print.manage', '管理打印', 'operations'),
  ('reports.view', '查看报表', 'operations'),
  ('security.view', '查看安全事件', 'operations'),
  ('documents.view', '查看业务文档', 'operations'),
  ('documents.print', '打印业务文档', 'operations'),
  ('documents.template.manage', '管理文档模板', 'operations'),
  ('analytics.view.store', '查看门店经营报表', 'analytics'),
  ('analytics.view.tenant', '查看全院经营报表', 'analytics'),
  ('analytics.export', '导出经营报表CSV', 'analytics'),
  ('medical_record.archive', '病历归档', 'compliance'),
  ('medical_record.amend.request', '病历修订申请', 'compliance'),
  ('medical_record.amend.approve', '病历修订审批', 'compliance'),
  ('veterinarian_registration.read', '查看执业兽医备案', 'compliance'),
  ('veterinarian_registration.manage', '管理执业兽医备案', 'compliance'),
  ('license.read', '查看动物诊疗许可证', 'compliance'),
  ('license.manage', '管理动物诊疗许可证', 'compliance'),
  ('regulatory_report.read', '查看年度诊疗活动报告', 'compliance'),
  ('regulatory_report.generate', '生成年度诊疗活动报告', 'compliance'),
  ('regulatory_report.submit', '提交年度诊疗活动报告', 'compliance'),
  ('epidemic.read', '查看疫情事件台账', 'compliance'),
  ('epidemic.report', '上报/维护疫情事件', 'compliance'),
  ('epidemic.resolve', '解除疫情事件', 'compliance'),
  ('waste.read', '查看医疗废弃物台账', 'compliance'),
  ('waste.manage', '管理医疗废弃物台账', 'compliance'),
  ('audit.view', '查看审计日志', 'core'),
  ('audit.export', '导出审计日志', 'core'),
  ('approval.inbox.view', '查看审批中心', 'core'),
  ('settings.tenant.read', '查看医院设置', 'core'),
  ('settings.tenant.manage', '管理医院设置', 'core'),
  ('settings.store.read', '查看门店设置', 'core'),
  ('settings.store.manage', '管理门店设置', 'core'),
  ('platform.tenant.list', '平台租户列表', 'platform'),
  ('platform.tenant.read', '查看租户详情', 'platform'),
  ('platform.tenant.suspend', '停用租户', 'platform'),
  ('platform.tenant.resume', '恢复租户', 'platform')
on conflict (code) do update set
  name = excluded.name,
  module = excluded.module;

-- 演示数据(可选):给指定账号设置演示权限(把邮箱换成你的登录账号)
update public.profiles
set permissions = array[
  'pages.general:browse',
  'pages.form:browse',
  'pages.list:browse',
  'pages.shop:browse'
]
where account = 'admin@example.com';

-- standard_module 示例数据(幂等)
insert into public.standard_module (title)
select v.title
from (values
  ('示例标题一'),
  ('示例标题二'),
  ('示例标题三')
) as v(title)
where not exists (
  select 1 from public.standard_module
  where title = v.title
);
