// 权限码与前端 views 的 meta.auth 对应;角色配置勾选基于此清单
// MXQ-3008/3010:新增门店归档/恢复、员工邀请/启停、角色权限编辑
export const PERMISSIONS = [
  { code: 'system:user:manage', label: '用户管理' },
  { code: 'system:role:manage', label: '角色管理' },
  { code: 'system:store:manage', label: '店铺管理' },
  { code: 'system.user.create', label: '创建用户' },
  { code: 'system.user.resetPassword', label: '重置用户密码' },
  { code: 'store:view', label: '查看门店' },
  { code: 'store.create', label: '创建门店' },
  { code: 'store.update', label: '编辑门店' },
  { code: 'store.archive', label: '归档门店' },
  { code: 'store.restore', label: '恢复门店' },
  { code: 'tenant.membership.create', label: '添加租户成员' },
  { code: 'tenant.membership.update', label: '更新租户成员' },
  { code: 'employee.create', label: '创建员工' },
  { code: 'employee.update', label: '编辑员工' },
  { code: 'employee.invite', label: '邀请员工' },
  { code: 'employee.disable', label: '停用员工' },
  { code: 'employee.enable', label: '启用员工' },
  { code: 'employee.assignStore', label: '分配门店' },
  { code: 'employee.changeRole', label: '变更角色' },
  { code: 'role.create', label: '创建角色' },
  { code: 'role.update', label: '编辑角色' },
  { code: 'role.permission.update', label: '编辑角色权限' },
  // MXQ-4001~4007:文件领域权限
  { code: 'file.upload', label: '上传文件' },
  { code: 'file.download', label: '下载文件' },
  { code: 'file.archive', label: '归档文件' },
  { code: 'file.delete', label: '删除文件' },
  // ===== MXQ-5001~5010:CRM 领域(客户/宠物)权限 =====
  { code: 'customer.view', label: '查看客户' },
  { code: 'customer.create', label: '创建客户' },
  { code: 'customer.update', label: '编辑客户' },
  { code: 'customer.archive', label: '归档客户' },
  { code: 'customer.merge', label: '合并客户' },
  { code: 'customer.import', label: '导入客户' },
  { code: 'pet.view', label: '查看宠物' },
  { code: 'pet.create', label: '创建宠物' },
  { code: 'pet.update', label: '编辑宠物' },
  // ===== MXQ-6001~6010:Catalog 领域(统一目录)权限 =====
  { code: 'catalog.view', label: '查看目录' },
  { code: 'catalog.manage', label: '管理目录' },
  { code: 'catalog.storePrice.manage', label: '管理门店价格' },
  { code: 'catalog.drug.manage', label: '管理药品扩展' },
  { code: 'catalog.vaccine.manage', label: '管理疫苗扩展' },
  // ===== MXQ-7001~7011:Clinical 领域(诊疗核心)权限 =====
  { code: 'appointment.view', label: '查看预约' },
  { code: 'appointment.manage', label: '管理预约' },
  { code: 'encounter.view', label: '查看病历' },
  { code: 'encounter.work', label: '接诊编辑' },
  { code: 'encounter.sign', label: '签署病历' },
  { code: 'encounter.revise', label: '修订病历' },
  { code: 'prescription.view', label: '查看处方' },
  { code: 'prescription.create', label: '开具处方' },
  { code: 'prescription.dispense', label: '发药' },
  { code: 'nurse_task.view', label: '查看护士任务' },
  { code: 'nurse_task.manage', label: '管理护士任务' },
  // ===== MXQ-8001~8007:Billing 领域(收费收银)权限 =====
  { code: 'invoice.view', label: '查看发票' },
  { code: 'invoice.create', label: '创建发票' },
  { code: 'invoice.confirm', label: '确认发票' },
  { code: 'invoice.cancel', label: '取消发票' },
  { code: 'payment.process', label: '处理支付' },
  { code: 'refund.process', label: '处理退款' },
  { code: 'receipt.print', label: '打印小票' },
  // ===== MXQ-9001~9008:Inventory 领域(库存管理)权限 =====
  { code: 'inventory.view', label: '查看库存' },
  { code: 'inventory.receive', label: '入库' },
  { code: 'inventory.dispense', label: '发药' },
  { code: 'inventory.count', label: '盘点' },
  { code: 'inventory.transfer', label: '调拨' },
  { code: 'inventory.manage', label: '仓库管理' },
  // ===== MXQ-10001~10011:Diagnostics 领域(疫苗/驱虫/检验/提醒)权限 =====
  { code: 'vaccine.view', label: '查看疫苗' },
  { code: 'vaccine.manage', label: '管理疫苗' },
  { code: 'vaccine.certificate.issue', label: '签发疫苗证明' },
  { code: 'deworming.view', label: '查看驱虫' },
  { code: 'deworming.manage', label: '管理驱虫' },
  { code: 'lab.view', label: '查看检验' },
  { code: 'lab.request', label: '申请检验' },
  { code: 'lab.collect', label: '采集标本' },
  { code: 'lab.result.input', label: '录入结果' },
  { code: 'lab.result.review', label: '审核结果' },
  { code: 'lab.critical.acknowledge', label: '确认危急值' },
  { code: 'diag_reminder.view', label: '查看提醒' },
  // ===== MXQ-11001~11009:Inpatient 领域(住院管理)权限 =====
  { code: 'inpatient.view', label: '查看住院' },
  { code: 'inpatient.admit', label: '办理入院' },
  { code: 'inpatient.discharge', label: '办理出院' },
  { code: 'inpatient.transfer', label: '换房' },
  { code: 'nursing.view', label: '查看护理' },
  { code: 'nursing.manage', label: '管理护理' },
  { code: 'handover.manage', label: '交接班' },
  // ===== MXQ-12001~12009:Operations 领域(运营管理)权限 =====
  { code: 'membership.view', label: '查看会员等级' },
  { code: 'membership.manage', label: '管理会员等级' },
  { code: 'points.adjust', label: '调整积分' },
  { code: 'message.manage', label: '管理消息模板' },
  { code: 'reminder.manage', label: '管理提醒' },
  { code: 'imports.manage', label: '管理导入任务' },
  { code: 'print.manage', label: '管理打印' },
  { code: 'reports.view', label: '查看报表' },
  { code: 'security.view', label: '查看安全事件' },
  // ===== S3.1-1:Compliance 合规域权限 =====
  { code: 'medical_record.archive', label: '病历归档' },
  { code: 'medical_record.amend.request', label: '病历修订申请' },
  { code: 'medical_record.amend.approve', label: '病历修订审批' },
  { code: 'veterinarian_registration.read', label: '查看执业兽医备案' },
  { code: 'veterinarian_registration.manage', label: '管理执业兽医备案' },
  { code: 'prescription.issue', label: '开具处方' },
  { code: 'prescription.extend_validity', label: '延长处方有效期' },
  { code: 'prescription.controlled_issue', label: '开具受控药品处方' },
] as const
